/*EFFECTED FOR USERS*/
INSERT INTO EFFECTED
VALUES(100);
INSERT INTO EFFECTED
VALUES(101);
INSERT INTO EFFECTED
VALUES(102);
INSERT INTO EFFECTED
VALUES(103);
INSERT INTO EFFECTED
VALUES(104);

/*CREATOR FOR USERS*/
INSERT INTO CREATOR
VALUES(100,100);
INSERT INTO CREATOR
VALUES(101,101);
INSERT INTO CREATOR
VALUES(102,102);
INSERT INTO CREATOR
VALUES(103,103);
INSERT INTO CREATOR
VALUES(104,104);

/*LINKEDIN USERS*/
INSERT INTO LINKEDIN_USER
VALUES(100,'DARON',NULL,'YONDEM',TO_DATE('1980-03-18','YYYY-MM-DD'),'905328654980','daronyondem@gmail.com','MVP_azure*123','FREE',100);
INSERT INTO LINKEDIN_USER
VALUES(101,'ELON',NULL,'MUSK',TO_DATE('1975-08-07','YYYY-MM-DD'),'12058546549','elon_tesla_spaceX@paypal.com','autonomVehicle3301','PREMIUM',101);
INSERT INTO LINKEDIN_USER
VALUES(102,'LARRY',NULL,'ELLISON',TO_DATE('1944-08-17','YYYY-MM-DD'),'898328654980','larryCEO@oracle.com','oracleDBCEOoracle','PREMIUM',102);
INSERT INTO LINKEDIN_USER
VALUES(103,'MARK','ELLIOT','ZUCKERBERG',TO_DATE('1984-08-14','YYYY-MM-DD'),'756328654980','mark_thief_of_data@facebook.com','Cassandra1408','FREE',103);
INSERT INTO LINKEDIN_USER
VALUES(104,'BURAK',NULL,'YANIK',TO_DATE('1996-05-28','YYYY-MM-DD'),'905328453980','buraky@ulutek.com','burak1996123456','FREE',104);

/*EFFECTIVE FOR COMMUNITY*/
INSERT INTO EFFECTED
VALUES(105);
INSERT INTO EFFECTED
VALUES(106);

/*CREATOR FOR COMMUNITY*/
INSERT INTO CREATOR
VALUES(105,105);
INSERT INTO CREATOR
VALUES(106,106);

/*COMMUNITY SUPERCLASS*/
INSERT INTO COMMUNITY
VALUES(100,103,'FACEBOOK','FACEBOOK IS A SOCIAL MEDIA PLATFORM',TO_DATE('2011-03-15','YYYY-MM-DD'),'COMPANY',105);
INSERT INTO COMMUNITY
VALUES(101,102,'ORACLE','ORACLE IS A DATABASE COMPANY',TO_DATE('2008-07-23','YYYY-MM-DD'),'COMPANY',106);

/*COUNTRY AND CITY FOR LOCATIONS*/
INSERT INTO COUNTRY
VALUES('CAN','CANADA');
INSERT INTO COUNTRY
VALUES('CHN','CHINA');
INSERT INTO COUNTRY
VALUES('CZE','CZECH REPUBLIC');
INSERT INTO COUNTRY
VALUES('DNK','DENMARK');
INSERT INTO COUNTRY
VALUES('UKR','UKRAINE');

INSERT INTO CITY
VALUES('CAN','TORONTO');
INSERT INTO CITY
VALUES('CAN','OTTAWA');
INSERT INTO CITY
VALUES('CHN','PEKIN');
INSERT INTO CITY
VALUES('CHN','SHANGHAI');
INSERT INTO CITY
VALUES('CZE','PRAGUE');
INSERT INTO CITY
VALUES('DNK','KOPHENAGEN');
INSERT INTO CITY
VALUES('DNK','HOLSTEBRO');
INSERT INTO CITY
VALUES('UKR','KIEV');


/*CREATOR PROFILE FOR USERS*/
INSERT INTO CREATOR_PROFILE
VALUES(100,'profile_images/daron.jpeg',NULL,'USER',100,'DNK','KOPHENAGEN');
INSERT INTO CREATOR_PROFILE
VALUES(101,'profile_images/elon.jpeg',NULL,'USER',101,'CAN','TORONTO');
INSERT INTO CREATOR_PROFILE
VALUES(102,'profile_images/ellison.jpeg',NULL,'USER',102,'CAN','OTTAWA');
INSERT INTO CREATOR_PROFILE
VALUES(103,'profile_images/mark_in_office.jpeg',NULL,'USER',103,'CZE','PRAGUE');
INSERT INTO CREATOR_PROFILE
VALUES(104,'profile_images/burak.jpeg',NULL,'USER',104,'CHN','SHANGHAI');
/*FOR COMMUNITY*/
INSERT INTO CREATOR_PROFILE
VALUES(105,'profile_images/facebook.jpeg','cover_photos/china-office-facebook','COMPANY',105,'CHN','SHANGHAI');
INSERT INTO CREATOR_PROFILE
VALUES(106,'profile_images/oracle.jpeg','cover_photos/toronto-office-oracle','COMPANY',106,'CAN','TORONTO');

/*USER PROFILE*/
INSERT INTO USER_PROFILE
VALUES(100);
INSERT INTO USER_PROFILE
VALUES(101);
INSERT INTO USER_PROFILE
VALUES(102);
INSERT INTO USER_PROFILE
VALUES(103);
INSERT INTO USER_PROFILE
VALUES(104);

/*COMPANY PROFILE*/
INSERT INTO USER_PROFILE
VALUES(105);
INSERT INTO USER_PROFILE
VALUES(106);

/* PROFILE INFO FOR USERS (SKILL,SCHOOL,EXPERIENCE)*/
INSERT INTO PROFILE_INFO
VALUES(100,100,'AZURE CLOUD','SKILL');
INSERT INTO PROFILE_INFO
VALUES(106,100,'MVC','SKILL');
INSERT INTO PROFILE_INFO
VALUES(107,100,'ASP.NET','SKILL');

INSERT INTO PROFILE_INFO
VALUES(101,101,'AI','SKILL');
INSERT INTO PROFILE_INFO
VALUES(108,101,'AUTONOMOUS VEHICLE','SKILL');

INSERT INTO PROFILE_INFO
VALUES(102,102,'PL/SQL','SKILL');
INSERT INTO PROFILE_INFO
VALUES(105,102,'DATABASE SYSTEMS','SKILL');

INSERT INTO PROFILE_INFO
VALUES(103,103,'CASSANDRA','SKILL');
INSERT INTO PROFILE_INFO
VALUES(109,103,'PHP','SKILL');

INSERT INTO PROFILE_INFO
VALUES(104,104,'ADO.NET','SKILL');
INSERT INTO PROFILE_INFO
VALUES(110,104,'REACT JS','SKILL');

INSERT INTO PROFILE_INFO
VALUES(111,100,'MANCHESTER UNIVERSITY','SCHOOL');
INSERT INTO PROFILE_INFO
VALUES(112,101,'MIT','SCHOOL');
INSERT INTO PROFILE_INFO
VALUES(113,102,'STANFORD UNIVERSITY','SCHOOL');
INSERT INTO PROFILE_INFO
VALUES(114,103,'HARVARD UNIVERSITY','SCHOOL');
INSERT INTO PROFILE_INFO
VALUES(115,104,'ULUDAG UNIVERSITY','SCHOOL');

INSERT INTO PROFILE_INFO
VALUES(116,100,'MICROSOFT','EXPERIENCE');
INSERT INTO PROFILE_INFO
VALUES(117,101,'SPACE X','EXPERIENCE');
INSERT INTO PROFILE_INFO
VALUES(118,102,'ORACLE','EXPERIENCE');
INSERT INTO PROFILE_INFO
VALUES(119,103,'FACEBOOK','EXPERIENCE');
INSERT INTO PROFILE_INFO
VALUES(120,104,'ULUTEK IT INTERN','EXPERIENCE');

/*COMPANY*/
INSERT INTO COMPANY
VALUES(100,103,'100000+');
INSERT INTO COMPANY
VALUES(101,102,'10000+');

/*COMPANY PROFILE*/
INSERT INTO COMPANY_PROFILE
VALUES(105,'www.facebook.com','info@facebook.com','SAN FRANCISCO');
INSERT INTO COMPANY_PROFILE
VALUES(106,'www.oracle.com','info@oracle.com','SAN FRANCISCO');

/*EXPERIENCE*/
INSERT INTO EXPERIENCE
VALUES(116,100,'AZURE CLOUD DEVELOPER','AZURE ILE ILGILI EGITIM VERILDI GELISTIRMELER YAPILDI',
        TO_DATE('2010-06-25','YYYY-MM-DD'),TO_DATE('2015-12-30','YYYY-MM-DD'));
INSERT INTO EXPERIENCE
VALUES(117,101,'CEO','ROKET ATTIK UZAYA YETMEDI ARABA GONDERDIK',
        TO_DATE('2013-02-05','YYYY-MM-DD'),NULL);
INSERT INTO EXPERIENCE
VALUES(118,102,'CEO','DUNYANINN EN HIZLI VERITABANINI BIZ YAPIYOZ',
        TO_DATE('2005-06-25','YYYY-MM-DD'),NULL);
INSERT INTO EXPERIENCE
VALUES(119,103,'CEO AND CTO','FACEBOOK UN SAHIBIYIM AYNI ZAMANDA PHP DEVELOPER OLARAK CALISIYOM',
        TO_DATE('2005-08-05','YYYY-MM-DD'),NULL);
INSERT INTO EXPERIENCE
VALUES(120,104,'INTERN','COZUM ODAKLI WEB VE MOBIL UYGULAMA GELISTIRILMESI SURECLERINDE GOREVLENDIRILDIM',
        TO_DATE('2014-01-25','YYYY-MM-DD'),TO_DATE('2014-03-21','YYYY-MM-DD'));

/*ACTION FOR POST(BURAK,ELLISON AND MARK)*/
INSERT INTO ACTION
VALUES(100,'POST',104,104,TO_DATE(SYSDATE,'DD/MM/YYYY'));
INSERT INTO ACTION
VALUES(101,'POST',104,104,TO_DATE(SYSDATE,'DD/MM/YYYY'));
INSERT INTO ACTION
VALUES(102,'POST',102,102,TO_DATE(SYSDATE,'DD/MM/YYYY'));
INSERT INTO ACTION
VALUES(103,'POST',103,103,TO_DATE(SYSDATE,'DD/MM/YYYY'));

/*POST DETAILS*/
INSERT INTO POST
VALUES(100,'BAGLANTILARIMIN DIKKATINE AKTIF IS ARAYISINDA BULUNMAKTAYIM C# VE JAVA BILMEKTEYIM','MY CONNECTIONS',
104,NULL);
INSERT INTO POST
VALUES(101,'GUNAYDIN BUGUN DUNYA DEVELOPER GUNU','PUBLIC',
104,NULL);
INSERT INTO POST
VALUES(102,'ORACLE EN IYI DATABASE','PUBLIC',102,NULL);
INSERT INTO POST
VALUES(103,'CASSANDRA YAPTIK COK FENA OLDU','PUBLIC',103,NULL);

/*HASHTAGS*/
INSERT INTO HASHTAG
VALUES('#ORACLE');
INSERT INTO HASHTAG
VALUES('#DATABASE');
INSERT INTO HASHTAG
VALUES('#AI');
INSERT INTO HASHTAG
VALUES('#IMAGE PROCESSING');
INSERT INTO HASHTAG
VALUES('#DEVELOPER');
INSERT INTO HASHTAG
VALUES('#NETWORK TECHNOLOGY');
INSERT INTO HASHTAG
VALUES('#MICROSOFT');
INSERT INTO HASHTAG
VALUES('#.NET');
INSERT INTO HASHTAG
VALUES('#UML');
INSERT INTO HASHTAG
VALUES('#DATA MINING');
INSERT INTO HASHTAG
VALUES('#REACT');
INSERT INTO HASHTAG
VALUES('#VIRTUAL REALITY');
INSERT INTO HASHTAG
VALUES('#SPACE X');
INSERT INTO HASHTAG
VALUES('#TECHNOLOGY');
INSERT INTO HASHTAG
VALUES('#NEWS');
INSERT INTO HASHTAG
VALUES('#BIG DATA');

/*HASHTAG IN POST*/
INSERT INTO POST_CONTAINS_HASHTAG
VALUES(102,'#ORACLE');
INSERT INTO POST_CONTAINS_HASHTAG
VALUES(102,'#DATABASE');
INSERT INTO POST_CONTAINS_HASHTAG
VALUES(101,'#DEVELOPER');


