ALTER TABLE ADS
ADD(CONSTRAINT ADS_FK1 FOREIGN KEY(CreatorId)
REFERENCES CREATOR(CreatorId) ON DELETE CASCADE);

ALTER TABLE JOB_ANNOUNCEMENT
ADD(CONSTRAINT JOB_FK1 FOREIGN KEY(CreatorId)
REFERENCES CREATOR(CreatorId) ON DELETE CASCADE);

ALTER TABLE USER_PROFILE
ADD(CONSTRAINT USER_PROFILE_FK1 FOREIGN KEY(LIVECITYCOUNTRY,LIVECITYNAME)
REFERENCES CITY(COUNTRYCODE,CITYNAME) ON DELETE SET NULL,
CONSTRAINT USER_PROFILE_FK2 FOREIGN KEY( HOMETOWNCITYCOUNTRY,HOMETOWNCITYNAME )
REFERENCES CITY(COUNTRYCODE,CITYNAME) ON DELETE SET NULL,
CONSTRAINT USER_PROFILE_FK3 FOREIGN KEY(CreatorId)
REFERENCES CREATOR(CreatorId) ON DELETE CASCADE);
    
ALTER TABLE USER_SETTINGS
ADD CONSTRAINT USER_SETTINGS_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE;
    
ALTER TABLE PAGE_SETTINGS
ADD CONSTRAINT PAGE_SETTINGS_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE;
    
ALTER TABLE GROUP_SETTINGS
ADD CONSTRAINT GROUP_SETTINGS_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE;
    
ALTER TABLE COMMUNITY_ROLE
ADD (CONSTRAINT COMMUNITY_ROLE_FK FOREIGN KEY (OwnerId)
    REFERENCES FACEBOOK_USER(UserId) ON DELETE CASCADE,
    CONSTRAINT COMMUNITY_ROLE_FK2 FOREIGN KEY (CommunityId,UserId)
    REFERENCES COMMUNITY(CommunityId,UserId) ON DELETE CASCADE);

ALTER TABLE CREATOR_NOTIFICATION
ADD (CONSTRAINT CREATOR_NOTIFICATION_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE,
    CONSTRAINT CREATOR_NOTIFICATION_FK2 FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE);
    
ALTER TABLE BOOKMARK
ADD (CONSTRAINT BOOKMARK_FK FOREIGN KEY (UserId)
    REFERENCES FACEBOOK_USER(UserId) ON DELETE CASCADE,
    CONSTRAINT BOOKMARK_FK2 FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE);
    
/* EFFECTED */
CREATE SEQUENCE Effected_Seq START WITH 1;

ALTER TABLE STORY
ADD CONSTRAINT STORY_FK FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE;
    
ALTER TABLE EVENT
ADD CONSTRAINT EVENT_FK FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE;  
    
ALTER TABLE POST
ADD CONSTRAINT POST_FK FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE;
    
ALTER TABLE ALBUM
ADD CONSTRAINT ALBUM_FK FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE;

ALTER TABLE FRIENDSHIP
ADD CONSTRAINT FRIENDSHIP_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE; 
    
ALTER TABLE GROUP_JOIN
ADD CONSTRAINT GROUP_JOIN_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;
    
ALTER TABLE CREATOR_LIKE
ADD CONSTRAINT CREATOR_LIKE_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;
    
ALTER TABLE FOLLOW
ADD CONSTRAINT FOLLOW_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;
    
ALTER TABLE REVIEW
ADD CONSTRAINT REVIEW_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;
    
ALTER TABLE MESSAGE
ADD CONSTRAINT MESSAGE_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;

ALTER TABLE USER_BLOCK
ADD CONSTRAINT USER_BLOCK_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;

ALTER TABLE USER_REPORT
ADD CONSTRAINT USER_REPORT_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE;
    
ALTER TABLE CITY
ADD CONSTRAINT CITY_FK FOREIGN KEY (CountryCode)
    REFERENCES COUNTRY(Code) ON DELETE CASCADE;

/* COUNTRY */
/* CATEGORY */

ALTER TABLE CREATOR
ADD CONSTRAINT CREATOR_FK FOREIGN KEY (EffectedId)
    REFERENCES EFFECTED(EffectedId) ON DELETE CASCADE;
    
ALTER TABLE FACEBOOK_USER
ADD CONSTRAINT FACEBOOK_USER_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE;
    
ALTER TABLE COMMUNITY
ADD (CONSTRAINT COMMUNITY_FK FOREIGN KEY (UserId)
    REFERENCES FACEBOOK_USER(UserId) ON DELETE CASCADE,
    CONSTRAINT COMMUNITY_FK2 FOREIGN KEY (CategoryName)
    REFERENCES COMMUNITY_CATEGORY(CategoryName) ON DELETE CASCADE,
    CONSTRAINT COMMUNITY_FK3 FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE);  
    
ALTER TABLE PAGE
ADD (CONSTRAINT PAGE_FK FOREIGN KEY (CommunityId,UserId)
    REFERENCES COMMUNITY(CommunityId,UserId) ON DELETE CASCADE,
    CONSTRAINT PAGE_FK2 FOREIGN KEY (CityCountry,CityName)
    REFERENCES CITY(CountryCode,CityName) ON DELETE SET NULL);
    
ALTER TABLE GROUP_FACEBOOK
ADD (CONSTRAINT GROUP_FACEBOOK_FK FOREIGN KEY (UserId,CommunityId)
    REFERENCES COMMUNITY(UserId,CommunityId) ON DELETE CASCADE);

ALTER TABLE PROFILE_INFO
ADD (CONSTRAINT PROFILE_INFO_FK FOREIGN KEY (ProfileId)
    REFERENCES USER_PROFILE(ProfileId) ON DELETE CASCADE,
    CONSTRAINT PROFILE_INFO_FK2 FOREIGN KEY (CommunityId,UserId)
    REFERENCES PAGE(CommunityId,UserId) ON DELETE CASCADE);

ALTER TABLE VISUAL_CONTENT
ADD CONSTRAINT VISUAL_CONTENT_FK FOREIGN KEY (ActionId)
    REFERENCES CREATOR_SHARE(ActionId) ON DELETE CASCADE;
     
ALTER TABLE DOCUMENT
ADD (CONSTRAINT DOCUMENT_FK FOREIGN KEY (ActionId,ContentId)
    REFERENCES VISUAL_CONTENT(ActionId,ContentId) ON DELETE CASCADE);
  
ALTER TABLE MEDIA
ADD (CONSTRAINT MEDIA_FK FOREIGN KEY (ActionId,ContentId)
    REFERENCES VISUAL_CONTENT(ActionId,ContentId) ON DELETE CASCADE);
    
ALTER TABLE PHOTO
ADD (CONSTRAINT PHOTO_FK FOREIGN KEY (ActionId,ContentId)
    REFERENCES VISUAL_CONTENT(ActionId,ContentId) ON DELETE CASCADE);
    
ALTER TABLE VIDEO
ADD (CONSTRAINT VIDEO_FK FOREIGN KEY (ActionId,ContentId)
    REFERENCES VISUAL_CONTENT(ActionId,ContentId) ON DELETE CASCADE);
    
ALTER TABLE UNIVERSITY
ADD (CONSTRAINT UNIVERSITY_FK1 FOREIGN KEY (ProfileInfoId,CommunityId,UserId)
    REFERENCES PROFILE_INFO(ProfileId,CommunityId,UserId) ON DELETE CASCADE
    );
    
ALTER TABLE COMPANY
ADD (CONSTRAINT COMPANY_FK1 FOREIGN KEY (ProfileInfoId,CommunityId,UserId)
    REFERENCES PROFILE_INFO(ProfileId,CommunityId,UserId) ON DELETE CASCADE
    );

ALTER TABLE SKILL
ADD (CONSTRAINT SKILL_FK1 FOREIGN KEY (ProfileInfoId,CommunityId,UserId)
    REFERENCES PROFILE_INFO(ProfileId,CommunityId,UserId) ON DELETE CASCADE
    );
    
ALTER TABLE LANGUAGE_PROFILE_INFO
ADD (CONSTRAINT LANGUAGE_PROFILE_INFO_FK1 FOREIGN KEY (ProfileInfoId,CommunityId,UserId)
    REFERENCES PROFILE_INFO(ProfileId,CommunityId,UserId) ON DELETE CASCADE
    );
    
ALTER TABLE JOB_APPLY 
ADD(CONSTRAINT JOB_APPLY_FK FOREIGN KEY (AnnouncementId)
    REFERENCES JOB_ANNOUNCEMENT(AnnouncementId) ON DELETE CASCADE,
    CONSTRAINT JOB_APPLY_FK2 FOREIGN KEY (UserId)
    REFERENCES FACEBOOK_USER(UserId) ON DELETE CASCADE);
    
ALTER TABLE EVENT_JOIN_STATUS
ADD (CONSTRAINT JOIN_STATUS_FK FOREIGN KEY (UserId)
    REFERENCES FACEBOOK_USER(UserId) ON DELETE CASCADE,
    CONSTRAINT JOIN_STATUS_FK2 FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE) ;
    
ALTER TABLE TAG
ADD (CONSTRAINT TAG_FK FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE,
    CONSTRAINT TAG_FK2 FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE);
    
ALTER TABLE CREATOR_SHARE
ADD (CONSTRAINT SHARE_FK FOREIGN KEY (EffectedId)
    REFERENCES EFFECTED(EffectedId) ON DELETE CASCADE,
    CONSTRAINT SHARE_FK2 FOREIGN KEY (CountryCode,CityName)
    REFERENCES CITY(CountryCode,CityName) ON DELETE SET NULL);
    
ALTER TABLE CREATOR_COMMENT
ADD (CONSTRAINT CREATOR_COMMENT_FK FOREIGN KEY (ActionId)
    REFERENCES ACTION(ActionId) ON DELETE CASCADE,
    CONSTRAINT CREATOR_COMMENT_FK2 FOREIGN KEY (EffectedId)
    REFERENCES EFFECTED(EffectedId) ON DELETE CASCADE);
    
ALTER TABLE ACTION
ADD (CONSTRAINT ACTION_FK FOREIGN KEY (DestinationId)
    REFERENCES EFFECTED(EffectedId) ON DELETE CASCADE,
    CONSTRAINT ACTION_FK_2 FOREIGN KEY (CreatorId)
    REFERENCES CREATOR(CreatorId) ON DELETE CASCADE);   
