CREATE TABLE ADS(
AnnouncementId INT PRIMARY KEY,
Text NVARCHAR2(50) NOT NULL,
Age NVARCHAR2(10) NOT NULL,
Gender NVARCHAR2(10) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
PaymentType NVARCHAR2(10) NOT NULL,
Price NUMBER(10,2) NOT NULL,
PayorSsn NVARCHAR2(20) NOT NULL,
CreatorId INT NOT NULL,
CHECK (Age IN ('YOUNG','ADULT')),
CHECK (Gender IN ('MALE','FEMALE')),
CHECK (PaymentType IN ('CREDITCARD','PAYPAL')));

CREATE TABLE JOB_ANNOUNCEMENT(
AnnouncementId INT PRIMARY KEY,
Text NVARCHAR2(50) NOT NULL,
Salary INT,
AnnouncementDate DATE NOT NULL,
DeadLine DATE NOT NULL,
WorkType NVARCHAR2(10) NOT NULL,
CreatorId INT NOT NULL,
CHECK (WorkType IN ('FULLTIME','PARTTIME','INTERN')));

CREATE TABLE USER_PROFILE(
ProfileId INT PRIMARY KEY,
ProfilePicture NVARCHAR2(100),
Relation NVARCHAR2(30) NOT NULL,
LiveCityCountry NVARCHAR2(5),
LiveCityName NVARCHAR2(30),
HomeTownCityCountry NVARCHAR2(5),
HomeTownCityName NVARCHAR2(30),
CreatorId INT NOT NULL UNIQUE,
CHECK (Relation IN ('MARRIED','ENGAGED','SINGLE','IN A RELATIONSHIP')));

CREATE TABLE USER_SETTINGS(
UserSettingsId INT PRIMARY KEY,
IsActive NUMBER(1,0) NOT NULL,
ApplicationLanguage NVARCHAR2(20) NOT NULL,
TwoFactorAuthentication NUMBER(1,0) NOT NULL,
PostPrivacy NVARCHAR2(20) NOT NULL,
CreatorId INT NOT NULL,
CHECK (ApplicationLanguage IN ('ENGLISH','TURKISH','GERMAN','SPANISH','RUSSIAN')),
CHECK (PostPrivacy IN ('PUBLIC','ONLY ME','ONLY FRIENDS')));

CREATE TABLE PAGE_SETTINGS(
PageSettingsId INT PRIMARY KEY,
IsActive NUMBER(1,0) NOT NULL,
CreatorId INT NOT NULL
);
CREATE TABLE GROUP_SETTINGS(
PageSettingsId INT PRIMARY KEY,
IsActive NUMBER(1,0) NOT NULL,
CreatorId INT NOT NULL
);
CREATE TABLE COMMUNITY_ROLE(
UserId INT NOT NULL,
CommunityId INT NOT NULL,
OwnerId INT NOT NULL,
RoleType NVARCHAR2(20) NOT NULL,
CHECK (RoleType IN ('ADMIN','MODERATOR','EDITOR')),
CONSTRAINT CommunityRole_PK PRIMARY KEY (UserId,CommunityId)
);
CREATE TABLE CREATOR_NOTIFICATION(
CreatorId INT NOT NULL, 
ActionId INT NOT NULL,
NotificationContent NVARCHAR2(50) NOT NULL,
CONSTRAINT Notification_PK PRIMARY KEY (CreatorId,ActionId)
);
CREATE TABLE BOOKMARK(
UserId INT NOT NULL,
ActionId INT NOT NULL,
SavedDate DATE NOT NULL,
BookmarkLabel NVARCHAR2(50),
CONSTRAINT Bookmark_PK PRIMARY KEY (UserId,ActionId)
);

CREATE TABLE EFFECTED(
EffectedId INT PRIMARY KEY
);

CREATE TABLE STORY(
ActionId INT PRIMARY KEY
);

CREATE TABLE EVENT(
ActionId INT PRIMARY KEY,
EventName NVARCHAR2(50) NOT NULL
);
CREATE TABLE POST(
ActionId INT PRIMARY KEY,
PostContent NVARCHAR2(250) NOT NULL,
Privacy NVARCHAR2(20) NOT NULL,
CHECK (Privacy IN ('PUBLIC','ONLY ME','ONLY FRIENDS'))
);

CREATE TABLE ALBUM(
ActionId INT PRIMARY KEY,
AlbumName NVARCHAR2(50) NOT NULL,
AlbumDescription NVARCHAR2(250),
Privacy NVARCHAR2(20) NOT NULL,
CHECK (Privacy IN ('PUBLIC','ONLY ME','ONLY FRIENDS'))
);
CREATE TABLE FRIENDSHIP(
ActionId INT PRIMARY KEY,
Status NVARCHAR2(20) NOT NULL,
CHECK (Status IN ('PENDING','ACCEPTED','IGNORED'))
);
CREATE TABLE GROUP_JOIN(
ActionId INT PRIMARY KEY
);
CREATE TABLE CREATOR_LIKE(
ActionId INT PRIMARY KEY,
Emoji NVARCHAR2(20)
CHECK (Emoji IN ('ANGRY','HAPPY','SAD','SHY'))
);
CREATE TABLE FOLLOW(
ActionId INT PRIMARY KEY
);
CREATE TABLE REVIEW(
ActionId INT PRIMARY KEY,
Content NVARCHAR2(50) NOT NULL,
Rating NVARCHAR2(1) NOT NULL,
CHECK (Rating IN ('1','2','3','4','5'))
);
CREATE TABLE MESSAGE(
ActionId INT PRIMARY KEY,
Text NVARCHAR2(200) NOT NULL
);
CREATE TABLE USER_BLOCK(
ActionId INT PRIMARY KEY
);
CREATE TABLE USER_REPORT(
ActionId INT PRIMARY KEY,
Reason NVARCHAR2(50) NOT NULL,
ReportContent NVARCHAR2(200)
);
CREATE TABLE CITY(
CountryCode NVARCHAR2(5), 
CityName NVARCHAR2(30) NOT NULL,
CONSTRAINT City_PK PRIMARY KEY (CountryCode,CityName)
);
CREATE TABLE COUNTRY(
Code NVARCHAR2(5) PRIMARY KEY,
CountryName NVARCHAR2(50) NOT NULL
);
CREATE TABLE COMMUNITY_CATEGORY(
CategoryName NVARCHAR2(50) PRIMARY KEY,
CategoryDescription NVARCHAR2(100) NOT NULL
);
CREATE TABLE ACTION(
ActionId INT PRIMARY KEY,
ActionType NVARCHAR2(30) NOT NULL,
CreatorId INT NOT NULL,
DestinationId INT NOT NULL,
ActionDate DATE NOT NULL,
CHECK(ActionType IN ('REPORT','BLOCK','MESSAGE','REVIEW','SHARE','FOLLOW','LIKE','COMMENT','JOIN','FRIENDSHIP'))
);
CREATE TABLE CREATOR_COMMENT(
ActionId INT PRIMARY KEY,
CommentContent NVARCHAR2(200) NOT NULL, 
EffectedId INT NOT NULL
);

CREATE TABLE CREATOR_SHARE(
ActionId INT PRIMARY KEY,
ShareContent NVARCHAR2(200),
ShareType NVARCHAR2(10) NOT NULL,
EffectedId INT NOT NULL,
CountryCode NVARCHAR2(5),
CityName NVARCHAR2(30),
ParentId INT ,
CHECK (ShareType IN ('EVENT','POST','ALBUM','STORY'))
);

/* erco region */
CREATE TABLE CREATOR(
CreatorId INT ,
EffectedId INT ,
PRIMARY KEY(CreatorId)
);

CREATE TABLE FACEBOOK_USER(
UserId INT ,
Fname NVARCHAR2(50) NOT NULL ,
Mname NVARCHAR2(50) ,
Lname NVARCHAR2(50) NOT NULL ,
Birthday DATE NOT NULL,
Gender NVARCHAR2(6) NOT NULL,
Phone NVARCHAR2(13),
Email NVARCHAR2(50) NOT NULL,
UserPassword NVARCHAR2(20) NOT NULL,
CreatorId INT,
CHECK (Gender IN ('MALE', 'FEMALE')),
PRIMARY KEY (UserId)
);

CREATE TABLE COMMUNITY(
CommunityId INT ,
UserId INT  ,
CommunityName NVARCHAR2(200) NOT NULL,
CreatedDate DATE NOT NULL,
ProfilePhoto NVARCHAR2(100),
CoverPhoto NVARCHAR2(100),
CategoryName NVARCHAR2(15) NOT NULL,
CommunityType NVARCHAR2(7) NOT NULL,
CreatorId INT,
CHECK (CommunityType IN ('PAGE', 'GROUP')),
PRIMARY KEY (CommunityId,UserId)
);

CREATE TABLE PAGE(
CommunityId INT ,
UserId INT  ,
Phone NVARCHAR2(13),
Website NVARCHAR2(100),
Email NVARCHAR2(50) NOT NULL,
OpeningHours NVARCHAR2(5),
ClosingHours NVARCHAR2(5),
CityCountry NVARCHAR2(5),
CityName NVARCHAR2(30),
PRIMARY KEY (CommunityId,UserId)
);

CREATE TABLE GROUP_FACEBOOK(
CommunityId INT ,
UserId INT  ,
PRIMARY KEY (CommunityId,UserId)
);

CREATE TABLE PROFILE_INFO(
ProfileId INT,
CommunityId INT,
UserId INT,
ProfileInfoType NVARCHAR2(10) NOT NULL,
CHECK (ProfileInfoType IN ('HIGH SCHOOL', 'COMPANY', 'SKILL', 'UNIVERSITY','LANGUAGE')),
PRIMARY KEY (ProfileId,CommunityId,UserId)
);

CREATE TABLE VISUAL_CONTENT(
ContentId INT ,
ActionId INT,
Url NVARCHAR2(100) NOT NULL,
ContentType NVARCHAR2(8) NOT NULL,
CHECK (ContentType IN ('DOCUMENT', 'MEDIA')),
PRIMARY KEY (ContentId,ActionId)
);

CREATE TABLE DOCUMENT(
ContentId INT ,
ActionId INT,
PRIMARY KEY (ContentId,ActionId)
);

CREATE TABLE MEDIA(
ContentId INT ,
ActionId INT,
MediaType NVARCHAR2(5) NOT NULL,
CHECK (MediaType IN ('PHOTO', 'VIDEO')),
PRIMARY KEY (ContentId,ActionId)
);

CREATE TABLE PHOTO(
ContentId INT ,
ActionId INT,
PRIMARY KEY (ContentId,ActionId)
);

CREATE TABLE VIDEO(
ContentId INT ,
ActionId INT,
PRIMARY KEY (ContentId,ActionId)
);

CREATE TABLE UNIVERSITY(
ProfileInfoId INT ,
CommunityId INT,
UserId INT,
Text NVARCHAR2(50),
StartDate DATE,
EndDate DATE,
PRIMARY KEY (ProfileInfoId,CommunityId,UserId)
);
CREATE TABLE COMPANY(
ProfileInfoId INT ,
CommunityId INT,
UserId INT,
Text NVARCHAR2(50),
StartDate DATE,
EndDate DATE,
PRIMARY KEY (ProfileInfoId,CommunityId,UserId)
);

CREATE TABLE SKILL(
ProfileInfoId INT ,
CommunityId INT,
UserId INT,
PRIMARY KEY (ProfileInfoId,CommunityId,UserId)
);

CREATE TABLE LANGUAGE_PROFILE_INFO(
ProfileInfoId INT ,
CommunityId INT,
UserId INT,
LanguageLevel NVARCHAR2(2),
CHECK (LanguageLevel IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
PRIMARY KEY (ProfileInfoId,CommunityId,UserId)
);

CREATE TABLE JOB_APPLY(
AnnouncementId INT ,
UserId INT,
JobResume NVARCHAR2(100) NOT NULL,
ApplyDate DATE,
PRIMARY KEY (AnnouncementId,UserId)
);

CREATE TABLE EVENT_JOIN_STATUS(
ActionId INT ,
UserId INT,
Status  NVARCHAR2(10) NOT NULL,
CHECK (Status IN ('GOING', 'INTERESTED')),
PRIMARY KEY (ActionId,UserId)
);

CREATE TABLE TAG(
CreatorId INT ,
ActionId INT,
PRIMARY KEY (ActionId,CreatorId)
);